x-postgresvars: &postgresvars
  POSTGRES_USER: osproject
  POSTGRES_PASSWORD: pnaeibpbiaparpipabpaib # type anything in here

x-webservervars: &webservervars
  <<: *postgresvars
  # create a google cloud project
  # then APIs & Services > Credentials > Create Credentials > OAuth Client IDs
  # put in https://yoursite.com/login/google/callback
  # as an authorized redirect URI (or use http if https is not available)
  # OAuth Consent Screen scopes: none
  GOOGLE_AUTH_CLIENT_ID: 123abc123abc
  GOOGLE_AUTH_CLIENT_SECRET: asdasdasdasd

  # this should be the postgres container's name
  POSTGRES_HOSTNAME: postgres

  # https://kit.svelte.dev/docs/adapter-node
  # uncomment only if you are using a reverse proxy
  # PROTOCOL_HEADER: X-Forwarded-Proto
  # HOST_HEADER: X-Forwarded-Host

services:
  webserver:
    image: nutchapolsal/osproject
    environment:
      <<: *webservervars
    ports:
      - 3000:3000
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    environment:
      <<: *postgresvars
    volumes:
      - "osproject-data:/var/lib/postgresql/data"

volumes:
  osproject-data:
    name: osproject-data